numeric_vector <- c(1, 2, 3, 4, 5)
print("Numeric Vector:")
print(numeric_vector)
print("Type of numeric_vector:")
print(class(numeric_vector))
character_vector <- c("apple", "banana", "cherry", "date", "elderberry")
print("\nCharacter Vector:")
print(character_vector)
print("Type of character_vector:")
print(class(character_vector))
logical_vector <- c(TRUE, FALSE, TRUE, FALSE, TRUE)
print("\nLogical Vector:")
print(logical_vector)
print("Type of logical_vector:")
print(class(logical_vector))
